
package flow.MP.RedefineSenha;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RedefinirSenhaUsuariov1_PortType", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RedefinirSenhaUsuariov1PortType {


    /**
     * 
     * @param redefinirSenhaUsuarioInput
     * @return
     *     returns flow.MP.RedefineSenha.RedefinirSenhaUsuarioOutput
     * @throws ErroTecnicoFaultMsg
     * @throws RedefinirSenhaUsuarioFaultMsg
     */
    @WebMethod(action = "redefinirSenhaUsuario")
    @WebResult(name = "RedefinirSenhaUsuarioOutput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "RedefinirSenhaUsuarioOutput")
    public RedefinirSenhaUsuarioOutput redefinirSenhaUsuario(
        @WebParam(name = "RedefinirSenhaUsuarioInput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "RedefinirSenhaUsuarioInput")
        RedefinirSenhaUsuarioInput redefinirSenhaUsuarioInput)
        throws ErroTecnicoFaultMsg, RedefinirSenhaUsuarioFaultMsg
    ;

}
