
package flow.MP.RedefineSenha;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RedefinirSenhaUsuarioFault", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
public class RedefinirSenhaUsuarioFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RedefinirSenhaUsuarioFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RedefinirSenhaUsuarioFaultMsg(String message, RedefinirSenhaUsuarioFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RedefinirSenhaUsuarioFaultMsg(String message, RedefinirSenhaUsuarioFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: flow.MP.RedefineSenha.RedefinirSenhaUsuarioFault
     */
    public RedefinirSenhaUsuarioFault getFaultInfo() {
        return faultInfo;
    }

}
