
package flow.MP.GeraAtendimento;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GerarAtendimentoFault", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
public class GerarAtendimentoFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GerarAtendimentoFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GerarAtendimentoFaultMsg(String message, GerarAtendimentoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GerarAtendimentoFaultMsg(String message, GerarAtendimentoFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: flow.MP.GeraAtendimento.GerarAtendimentoFault
     */
    public GerarAtendimentoFault getFaultInfo() {
        return faultInfo;
    }

}
