
package flow.MP.SolicitaExtrato;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SolicitarExtratoParticipanteFault", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
public class SolicitarExtratoParticipanteFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SolicitarExtratoParticipanteFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SolicitarExtratoParticipanteFaultMsg(String message, SolicitarExtratoParticipanteFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SolicitarExtratoParticipanteFaultMsg(String message, SolicitarExtratoParticipanteFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: flow.MP.SolicitaExtrato.SolicitarExtratoParticipanteFault
     */
    public SolicitarExtratoParticipanteFault getFaultInfo() {
        return faultInfo;
    }

}
