
package flow.MP.IdentificaParticipant;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IdentificarParticipantev1", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", wsdlLocation = "http://localhost:9999/IdentificarParticipantev1_Mock?WSDL")
public class IdentificarParticipantev1
    extends Service
{

    private final static URL IDENTIFICARPARTICIPANTEV1_WSDL_LOCATION;
    private final static WebServiceException IDENTIFICARPARTICIPANTEV1_EXCEPTION;
    private final static QName IDENTIFICARPARTICIPANTEV1_QNAME = new QName("http://ebs.multiplusfidelidade.com.br/v1", "IdentificarParticipantev1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/IdentificarParticipantev1_Mock?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTIFICARPARTICIPANTEV1_WSDL_LOCATION = url;
        IDENTIFICARPARTICIPANTEV1_EXCEPTION = e;
    }

    public IdentificarParticipantev1() {
        super(__getWsdlLocation(), IDENTIFICARPARTICIPANTEV1_QNAME);
    }

    public IdentificarParticipantev1(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTIFICARPARTICIPANTEV1_QNAME, features);
    }

    public IdentificarParticipantev1(URL wsdlLocation) {
        super(wsdlLocation, IDENTIFICARPARTICIPANTEV1_QNAME);
    }

    public IdentificarParticipantev1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTIFICARPARTICIPANTEV1_QNAME, features);
    }

    public IdentificarParticipantev1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentificarParticipantev1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IdentificarParticipantev1PortType
     */
    @WebEndpoint(name = "IdentificarParticipantev1")
    public IdentificarParticipantev1PortType getIdentificarParticipantev1() {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "IdentificarParticipantev1"), IdentificarParticipantev1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdentificarParticipantev1PortType
     */
    @WebEndpoint(name = "IdentificarParticipantev1")
    public IdentificarParticipantev1PortType getIdentificarParticipantev1(WebServiceFeature... features) {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "IdentificarParticipantev1"), IdentificarParticipantev1PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTIFICARPARTICIPANTEV1_EXCEPTION!= null) {
            throw IDENTIFICARPARTICIPANTEV1_EXCEPTION;
        }
        return IDENTIFICARPARTICIPANTEV1_WSDL_LOCATION;
    }

}
