
package flow.MP.IdentificaParticipant;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IdentificarParticipantev1_PortType", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IdentificarParticipantev1PortType {


    /**
     * 
     * @param identificarParticipanteInput
     * @return
     *     returns flow.MP.IdentificaParticipant.IdentificarParticipanteOutput
     * @throws IdentificarParticipanteFaultMsg
     * @throws ErroTecnicoFaultMsg
     */
    @WebMethod(action = "identificarParticipante")
    @WebResult(name = "IdentificarParticipanteOutput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "IdentificarParticipanteOutput")
    public IdentificarParticipanteOutput identificarParticipante(
        @WebParam(name = "IdentificarParticipanteInput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "IdentificarParticipanteInput")
        IdentificarParticipanteInput identificarParticipanteInput)
        throws ErroTecnicoFaultMsg, IdentificarParticipanteFaultMsg
    ;

}
