
package flow.MP.IdentificaParticipant;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IdentificarParticipanteFault", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
public class IdentificarParticipanteFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IdentificarParticipanteFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IdentificarParticipanteFaultMsg(String message, IdentificarParticipanteFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IdentificarParticipanteFaultMsg(String message, IdentificarParticipanteFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: flow.MP.IdentificaParticipant.IdentificarParticipanteFault
     */
    public IdentificarParticipanteFault getFaultInfo() {
        return faultInfo;
    }

}
