
package flow.MP.ConsultaSaldo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarSaldoParticipantev1", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", wsdlLocation = "http://localhost:9999/ConsultarSaldoParticipantev1_Mock?WSDL")
public class ConsultarSaldoParticipantev1
    extends Service
{

    private final static URL CONSULTARSALDOPARTICIPANTEV1_WSDL_LOCATION;
    private final static WebServiceException CONSULTARSALDOPARTICIPANTEV1_EXCEPTION;
    private final static QName CONSULTARSALDOPARTICIPANTEV1_QNAME = new QName("http://ebs.multiplusfidelidade.com.br/v1", "ConsultarSaldoParticipantev1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ConsultarSaldoParticipantev1_Mock?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARSALDOPARTICIPANTEV1_WSDL_LOCATION = url;
        CONSULTARSALDOPARTICIPANTEV1_EXCEPTION = e;
    }

    public ConsultarSaldoParticipantev1() {
        super(__getWsdlLocation(), CONSULTARSALDOPARTICIPANTEV1_QNAME);
    }

    public ConsultarSaldoParticipantev1(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARSALDOPARTICIPANTEV1_QNAME, features);
    }

    public ConsultarSaldoParticipantev1(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARSALDOPARTICIPANTEV1_QNAME);
    }

    public ConsultarSaldoParticipantev1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARSALDOPARTICIPANTEV1_QNAME, features);
    }

    public ConsultarSaldoParticipantev1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarSaldoParticipantev1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarSaldoParticipantev1PortType
     */
    @WebEndpoint(name = "ConsultarSaldoParticipantev1")
    public ConsultarSaldoParticipantev1PortType getConsultarSaldoParticipantev1() {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "ConsultarSaldoParticipantev1"), ConsultarSaldoParticipantev1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarSaldoParticipantev1PortType
     */
    @WebEndpoint(name = "ConsultarSaldoParticipantev1")
    public ConsultarSaldoParticipantev1PortType getConsultarSaldoParticipantev1(WebServiceFeature... features) {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "ConsultarSaldoParticipantev1"), ConsultarSaldoParticipantev1PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARSALDOPARTICIPANTEV1_EXCEPTION!= null) {
            throw CONSULTARSALDOPARTICIPANTEV1_EXCEPTION;
        }
        return CONSULTARSALDOPARTICIPANTEV1_WSDL_LOCATION;
    }

}
