
package flow.MP.AutenticaUsuario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutenticarUsuariov1", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", wsdlLocation = "http://localhost:9999/AutenticarUsuariov1_Mock?WSDL")
public class AutenticarUsuariov1
    extends Service
{

    private final static URL AUTENTICARUSUARIOV1_WSDL_LOCATION;
    private final static WebServiceException AUTENTICARUSUARIOV1_EXCEPTION;
    private final static QName AUTENTICARUSUARIOV1_QNAME = new QName("http://ebs.multiplusfidelidade.com.br/v1", "AutenticarUsuariov1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/AutenticarUsuariov1_Mock?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTENTICARUSUARIOV1_WSDL_LOCATION = url;
        AUTENTICARUSUARIOV1_EXCEPTION = e;
    }

    public AutenticarUsuariov1() {
        super(__getWsdlLocation(), AUTENTICARUSUARIOV1_QNAME);
    }

    public AutenticarUsuariov1(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTENTICARUSUARIOV1_QNAME, features);
    }

    public AutenticarUsuariov1(URL wsdlLocation) {
        super(wsdlLocation, AUTENTICARUSUARIOV1_QNAME);
    }

    public AutenticarUsuariov1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTENTICARUSUARIOV1_QNAME, features);
    }

    public AutenticarUsuariov1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutenticarUsuariov1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutenticarUsuariov1PortType
     */
    @WebEndpoint(name = "AutenticarUsuariov1")
    public AutenticarUsuariov1PortType getAutenticarUsuariov1() {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "AutenticarUsuariov1"), AutenticarUsuariov1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutenticarUsuariov1PortType
     */
    @WebEndpoint(name = "AutenticarUsuariov1")
    public AutenticarUsuariov1PortType getAutenticarUsuariov1(WebServiceFeature... features) {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "AutenticarUsuariov1"), AutenticarUsuariov1PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTENTICARUSUARIOV1_EXCEPTION!= null) {
            throw AUTENTICARUSUARIOV1_EXCEPTION;
        }
        return AUTENTICARUSUARIOV1_WSDL_LOCATION;
    }

}
