
package flow.MP.AutenticaUsuario;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AutenticarUsuarioFault", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
public class AutenticarUsuarioFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AutenticarUsuarioFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AutenticarUsuarioFaultMsg(String message, AutenticarUsuarioFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AutenticarUsuarioFaultMsg(String message, AutenticarUsuarioFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: flow.MP.AutenticaUsuario.AutenticarUsuarioFault
     */
    public AutenticarUsuarioFault getFaultInfo() {
        return faultInfo;
    }

}
