
package flow.MP.AutenticaUsuario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutenticarUsuariov1_PortType", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutenticarUsuariov1PortType {


    /**
     * 
     * @param autenticarUsuarioInput
     * @return
     *     returns flow.MP.AutenticaUsuario.AutenticarUsuarioOutput
     * @throws AutenticarUsuarioFaultMsg
     * @throws ErroTecnicoFaultMsg
     */
    @WebMethod(action = "autenticarUsuario")
    @WebResult(name = "AutenticarUsuarioOutput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "AutenticarUsuarioOutput")
    public AutenticarUsuarioOutput autenticarUsuario(
        @WebParam(name = "AutenticarUsuarioInput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "AutenticarUsuarioInput")
        AutenticarUsuarioInput autenticarUsuarioInput)
        throws AutenticarUsuarioFaultMsg, ErroTecnicoFaultMsg
    ;

}
