
package flow.MP.VerificaPermissao;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ErroTecnicoFault", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
public class ErroTecnicoFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErroTecnicoFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ErroTecnicoFaultMsg(String message, ErroTecnicoFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ErroTecnicoFaultMsg(String message, ErroTecnicoFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: flow.MP.VerificaPermissao.ErroTecnicoFault
     */
    public ErroTecnicoFault getFaultInfo() {
        return faultInfo;
    }

}
