
package flow.MP.VerificaPermissao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VerificarPermissaoAlteracaoCadastralv1", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", wsdlLocation = "http://localhost:9999/VerificarPermissaoAlteracaoCadastralv1_Mock?WSDL")
public class VerificarPermissaoAlteracaoCadastralv1
    extends Service
{

    private final static URL VERIFICARPERMISSAOALTERACAOCADASTRALV1_WSDL_LOCATION;
    private final static WebServiceException VERIFICARPERMISSAOALTERACAOCADASTRALV1_EXCEPTION;
    private final static QName VERIFICARPERMISSAOALTERACAOCADASTRALV1_QNAME = new QName("http://ebs.multiplusfidelidade.com.br/v1", "VerificarPermissaoAlteracaoCadastralv1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/VerificarPermissaoAlteracaoCadastralv1_Mock?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERIFICARPERMISSAOALTERACAOCADASTRALV1_WSDL_LOCATION = url;
        VERIFICARPERMISSAOALTERACAOCADASTRALV1_EXCEPTION = e;
    }

    public VerificarPermissaoAlteracaoCadastralv1() {
        super(__getWsdlLocation(), VERIFICARPERMISSAOALTERACAOCADASTRALV1_QNAME);
    }

    public VerificarPermissaoAlteracaoCadastralv1(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERIFICARPERMISSAOALTERACAOCADASTRALV1_QNAME, features);
    }

    public VerificarPermissaoAlteracaoCadastralv1(URL wsdlLocation) {
        super(wsdlLocation, VERIFICARPERMISSAOALTERACAOCADASTRALV1_QNAME);
    }

    public VerificarPermissaoAlteracaoCadastralv1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERIFICARPERMISSAOALTERACAOCADASTRALV1_QNAME, features);
    }

    public VerificarPermissaoAlteracaoCadastralv1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerificarPermissaoAlteracaoCadastralv1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VerificarPermissaoAlteracaoCadastralv1PortType
     */
    @WebEndpoint(name = "VerificarPermissaoAlteracaoCadastralv1")
    public VerificarPermissaoAlteracaoCadastralv1PortType getVerificarPermissaoAlteracaoCadastralv1() {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "VerificarPermissaoAlteracaoCadastralv1"), VerificarPermissaoAlteracaoCadastralv1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerificarPermissaoAlteracaoCadastralv1PortType
     */
    @WebEndpoint(name = "VerificarPermissaoAlteracaoCadastralv1")
    public VerificarPermissaoAlteracaoCadastralv1PortType getVerificarPermissaoAlteracaoCadastralv1(WebServiceFeature... features) {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "VerificarPermissaoAlteracaoCadastralv1"), VerificarPermissaoAlteracaoCadastralv1PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERIFICARPERMISSAOALTERACAOCADASTRALV1_EXCEPTION!= null) {
            throw VERIFICARPERMISSAOALTERACAOCADASTRALV1_EXCEPTION;
        }
        return VERIFICARPERMISSAOALTERACAOCADASTRALV1_WSDL_LOCATION;
    }

}
