
package flow.MP.VerificaPermissao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VerificarPermissaoAlteracaoCadastralv1_PortType", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VerificarPermissaoAlteracaoCadastralv1PortType {


    /**
     * 
     * @param verificarPermissaoAlteracaoCadastralInput
     * @return
     *     returns flow.MP.VerificaPermissao.VerificarPermissaoAlteracaoCadastralOutput
     * @throws VerificarPermissaoAlteracaoCadastralFaultMsg
     * @throws ErroTecnicoFaultMsg
     */
    @WebMethod(action = "verificarPermissaoAlteracaoCadastral")
    @WebResult(name = "VerificarPermissaoAlteracaoCadastralOutput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "VerificarPermissaoAlteracaoCadastralOutput")
    public VerificarPermissaoAlteracaoCadastralOutput verificarPermissaoAlteracaoCadastral(
        @WebParam(name = "VerificarPermissaoAlteracaoCadastralInput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "VerificarPermissaoAlteracaoCadastralInput")
        VerificarPermissaoAlteracaoCadastralInput verificarPermissaoAlteracaoCadastralInput)
        throws ErroTecnicoFaultMsg, VerificarPermissaoAlteracaoCadastralFaultMsg
    ;

}
