
package flow.MP.ConsultaParticipante;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarParticipantev1_PortType", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultarParticipantev1PortType {


    /**
     * 
     * @param consultarParticipanteInput
     * @return
     *     returns flow.MP.ValidaCliente.ConsultarParticipanteOutput
     * @throws ConsultarParticipanteFaultMsg
     * @throws ErroTecnicoFaultMsg
     */
    @WebMethod(action = "consultarParticipante")
    @WebResult(name = "ConsultarParticipanteOutput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "ConsultarParticipanteOutput")
    public ConsultarParticipanteOutput consultarParticipante(
        @WebParam(name = "ConsultarParticipanteInput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "ConsultarParticipanteInput")
        ConsultarParticipanteInput consultarParticipanteInput)
        throws ConsultarParticipanteFaultMsg, ErroTecnicoFaultMsg
    ;

}
