
package flow.MP.ConsultaParticipante;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ConsultarParticipanteFault", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
public class ConsultarParticipanteFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConsultarParticipanteFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ConsultarParticipanteFaultMsg(String message, ConsultarParticipanteFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ConsultarParticipanteFaultMsg(String message, ConsultarParticipanteFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: flow.MP.ValidaCliente.ConsultarParticipanteFault
     */
    public ConsultarParticipanteFault getFaultInfo() {
        return faultInfo;
    }

}
