
package flow.MP.EnviaEmail;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EnviarEmailParticipanteFault", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
public class EnviarEmailParticipanteFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EnviarEmailParticipanteFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public EnviarEmailParticipanteFaultMsg(String message, EnviarEmailParticipanteFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public EnviarEmailParticipanteFaultMsg(String message, EnviarEmailParticipanteFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: flow.MP.EnviaEmail.EnviarEmailParticipanteFault
     */
    public EnviarEmailParticipanteFault getFaultInfo() {
        return faultInfo;
    }

}
