
package flow.MP.EnviaEmail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnviarEmailParticipantev1_PortType", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnviarEmailParticipantev1PortType {


    /**
     * 
     * @param enviarEmailParticipanteInput
     * @return
     *     returns flow.MP.EnviaEmail.EnviarEmailParticipanteOutput
     * @throws ErroTecnicoFaultMsg
     * @throws EnviarEmailParticipanteFaultMsg
     */
    @WebMethod(action = "enviarEmailParticipante")
    @WebResult(name = "EnviarEmailParticipanteOutput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "EnviarEmailParticipanteOutput")
    public EnviarEmailParticipanteOutput enviarEmailParticipante(
        @WebParam(name = "EnviarEmailParticipanteInput", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", partName = "EnviarEmailParticipanteInput")
        EnviarEmailParticipanteInput enviarEmailParticipanteInput)
        throws EnviarEmailParticipanteFaultMsg, ErroTecnicoFaultMsg
    ;

}
