
package flow.MP.EnviaEmail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnviarEmailParticipantev1", targetNamespace = "http://ebs.multiplusfidelidade.com.br/v1", wsdlLocation = "http://localhost:9999/EnviarEmailParticipantev1_Mock?WSDL")
public class EnviarEmailParticipantev1
    extends Service
{

    private final static URL ENVIAREMAILPARTICIPANTEV1_WSDL_LOCATION;
    private final static WebServiceException ENVIAREMAILPARTICIPANTEV1_EXCEPTION;
    private final static QName ENVIAREMAILPARTICIPANTEV1_QNAME = new QName("http://ebs.multiplusfidelidade.com.br/v1", "EnviarEmailParticipantev1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/EnviarEmailParticipantev1_Mock?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENVIAREMAILPARTICIPANTEV1_WSDL_LOCATION = url;
        ENVIAREMAILPARTICIPANTEV1_EXCEPTION = e;
    }

    public EnviarEmailParticipantev1() {
        super(__getWsdlLocation(), ENVIAREMAILPARTICIPANTEV1_QNAME);
    }

    public EnviarEmailParticipantev1(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENVIAREMAILPARTICIPANTEV1_QNAME, features);
    }

    public EnviarEmailParticipantev1(URL wsdlLocation) {
        super(wsdlLocation, ENVIAREMAILPARTICIPANTEV1_QNAME);
    }

    public EnviarEmailParticipantev1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENVIAREMAILPARTICIPANTEV1_QNAME, features);
    }

    public EnviarEmailParticipantev1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnviarEmailParticipantev1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnviarEmailParticipantev1PortType
     */
    @WebEndpoint(name = "EnviarEmailParticipantev1")
    public EnviarEmailParticipantev1PortType getEnviarEmailParticipantev1() {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "EnviarEmailParticipantev1"), EnviarEmailParticipantev1PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnviarEmailParticipantev1PortType
     */
    @WebEndpoint(name = "EnviarEmailParticipantev1")
    public EnviarEmailParticipantev1PortType getEnviarEmailParticipantev1(WebServiceFeature... features) {
        return super.getPort(new QName("http://ebs.multiplusfidelidade.com.br/v1", "EnviarEmailParticipantev1"), EnviarEmailParticipantev1PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENVIAREMAILPARTICIPANTEV1_EXCEPTION!= null) {
            throw ENVIAREMAILPARTICIPANTEV1_EXCEPTION;
        }
        return ENVIAREMAILPARTICIPANTEV1_WSDL_LOCATION;
    }

}
